<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Models\Reservation;
use App\Models\Payment;
use App\Models\Company;
use App\Services\AccountingService;
use Illuminate\Support\Facades\DB;

class AccountingSyncReservations extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'accounting:sync-reservations';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate accounting entries for existing reservations that do not have them.';

    /**
     * Execute the console command.
     */
    public function handle(AccountingService $accountingService)
    {
        $reservations = Reservation::whereDoesntHave('payments')->get();

        if ($reservations->isEmpty()) {
            $this->info('No unsynced reservations found.');
            return;
        }

        $this->info("Found {$reservations->count()} reservations without accounting records. Syncing...");
        
        $companyId = Company::first()->id ?? null;
        if (!$companyId) {
            $this->error('No company found. Please seed a company first.');
            return;
        }

        $bar = $this->output->createProgressBar($reservations->count());
        $bar->start();

        foreach ($reservations as $reservation) {
            DB::transaction(function () use ($reservation, $accountingService, $companyId) {
                // 1. Create Payment record for the reservation fee
                $payment = Payment::create([
                    'company_id' => $companyId,
                    'customer_id' => $reservation->customer_id,
                    'reservation_id' => $reservation->id,
                    'amount' => $reservation->fee,
                    'payment_date' => $reservation->reservation_date,
                    'payment_method' => 'Initial Sync',
                    'reference_no' => 'SYNC-' . $reservation->id,
                    'notes' => 'Generated by accounting sync command.',
                ]);

                // 2. Generate Journal Entry
                $accountingService->recordReservationFeeReceipt($payment);
            });
            $bar->advance();
        }

        $bar->finish();
        $this->newLine();
        $this->info('Successfully synced all reservations to accounting.');
    }
}
